### ISSUE TITLE
Update Babel and its presets

### ISSUE THREAD

**Issue by RinatValiullov** [robb0wen/tornis#1]
I noticed in `package.json` that Babel's version is rather obsolete. The same is about:
```
...
"babel-core": "^6.26.3",
"babel-preset-env": "^1.7.0",
...

```

Is it possible update them without breaking library itself?

[Upgrade to Babel 7](https://babeljs.io/docs/en/v7-migration)

**Comment by robb0wen** [comment]
Thanks! I've just updated it. I wasn't using babel in my rollup script yet, but I've also added a transpiled ES5 version of the module for legacy browsers.
