### ISSUE TITLE
Invoking multiple times

### ISSUE THREAD

**Issue by bravokiloecho** [robb0wen/tornis#10]
Hi there, I'm excited to use this super handy tool.

I was just wondering how it would perform if the package was invoked several times across components in a Gatsby/Next/Nuxt kind of SPA. Would these create performance issues at all?

Or is there a better way to handle this?

**Comment by robb0wen** [comment]
Tornis uses a singleton pattern for the library itself so importing it into multiple components won't add extra any instances into memory. 

You can subscribe your watched functions when a component mounts, and so long as you unsubscribe the function when the component unmounts, you shouldn't see any memory leaks.
