### ISSUE TITLE
Error with SSR

### ISSUE THREAD

**Issue by florentbarriol** [robb0wen/tornis#2]
Hello,
Thanks for the great work on tornis ! 👏 

I encounter an error using tornis with a server-side rendering app.
Indeed, tornis use the `window` object in his contructor but in ssr mode the `window` object is not defined.
I make a workaround with a bridge which give me `noop` function in server side and tornis in client side.

`const isServer = typeof window === 'undefined';
let tornis = { watchViewport: _.noop, unwatchViewport: _.noop };
if (!isServer) {
  tornis = require('tornis');
}
const { watchViewport, unwatchViewport } = tornis;`

It will be great to add a security/condition in the constructor to avoid this kind of problem.
Do you want me to open a PR to fix this issue ?

**Comment by robb0wen** [comment]
Thanks for flagging that up! 
I've pushed a fix for it, and I've republished to NPM.

**Comment by florentbarriol** [comment]
Thanks a lot for the fix 🎉 
I will check it during the week
