### ISSUE TITLE
Add Type Definitions

### ISSUE THREAD

**Issue by taverasmisael** [robb0wen/tornis#3]
Hello and thanks for the great work on Tornis! 👏

I would love if this project had Type Definitions in order to include it in projects using TypeScript, but I don't know your thoughts on the topic, so please let me know. I have a fork of the project and I would love to contribute with that if its something you would like and add value to the library of course.

**Comment by robb0wen** [comment]
I'm not all too familiar with TypeScript myself, but if the addition of type definitions could be done in a way that had no adverse effect on the standard module usage, I'd be open to it.

**Comment by taverasmisael** [comment]
Thanks, I'll be opening a PR with the TS Typings. Thanks!

**Comment by robb0wen** [comment]
Merged, and published to npm in v0.1.5
